name: Build Android Flavors

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-flavors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter pub get (root)
        run: flutter pub get

      - name: Build SUNMI AAB
        working-directory: example
        run: |
          flutter pub get
          flutter build appbundle --flavor sunmi -t lib/main.dart

      - name: Upload SUNMI AAB
        uses: actions/upload-artifact@v4
        with:
          name: sunmi-aab
          path: example/build/app/outputs/bundle/release/*.aab

      - name: Build IMIN AAB
        working-directory: example
        run: |
          flutter pub get
          flutter build appbundle --flavor imin -t lib/main.dart

      - name: Upload IMIN AAB
        uses: actions/upload-artifact@v4
        with:
          name: imin-aab
          path: example/build/app/outputs/bundle/release/*.aab

      - name: Build GoogleGSM AAB
        working-directory: example
        run: |
          flutter pub get
          flutter build appbundle --flavor googlegsm -t lib/main.dart

      - name: Upload GoogleGSM AAB
        uses: actions/upload-artifact@v4
        with:
          name: googlegsm-aab
          path: example/build/app/outputs/bundle/release/*.aab
