name: camera_scanner_plugin_example
description: Example app for camera_scanner_plugin
version: 0.0.1
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera_scanner_plugin:
    path: ../

flutter:
  uses-material-design: true
